// R7 — projection confidence; R8 — variable spend projection.
import type { Confidence } from "./types";

/**
 * Confidence of a stored Transaction row (R7): already realized if its date
 * is today or earlier, otherwise CONFIRMED (a future installment, or a row
 * tied to a closed-unpaid invoice). RECURRING/PROJECTED values never come
 * from a stored Transaction — they're generated by the recurrence and
 * variable-spend projections below.
 */
export function classifyTransactionConfidence(competenceDate: string, today: string): Confidence {
  return competenceDate <= today ? "REALIZED" : "CONFIRMED";
}

/** Sums must never blend confidence levels silently (R7) — group instead of collapsing to one number. */
export function groupByConfidence<T extends { confidence: Confidence; amountCents: number }>(
  values: T[]
): Record<Confidence, number> {
  const totals: Record<Confidence, number> = {
    REALIZED: 0,
    CONFIRMED: 0,
    RECURRING: 0,
    PROJECTED: 0,
  };
  for (const v of values) totals[v.confidence] += v.amountCents;
  return totals;
}

/**
 * Average of a VARIABLE category's expenses over the last `lookback` closed
 * financial months (Settings.variableLookback). Returns null with fewer
 * closed months than that — projecting from n<lookback is less honest than
 * admitting there isn't enough history yet (R8).
 */
export function calculateVariableProjection(
  closedMonthExpensesCents: number[],
  lookback: number
): number | null {
  if (closedMonthExpensesCents.length < lookback) return null;

  const recent = closedMonthExpensesCents.slice(-lookback);
  const sum = recent.reduce((total, v) => total + v, 0);
  return Math.round(sum / lookback);
}

export interface MonthlyProjectionInputs {
  expectedIncomeCents: number;
  expectedAccountExpensesCents: number;
  invoicesDueCents: number;
  scheduledContributionsCents: number;
}

/**
 * Projected balance series starting at today's balance (series[0]), then one
 * entry per future month applying R8's recurrence formula. By construction
 * series[0] always equals the balance available today.
 */
export function calculateProjectedBalanceSeries(
  currentBalanceCents: number,
  futureMonths: MonthlyProjectionInputs[]
): number[] {
  const series = [currentBalanceCents];
  let previous = currentBalanceCents;

  for (const month of futureMonths) {
    const balance =
      previous +
      month.expectedIncomeCents -
      month.expectedAccountExpensesCents -
      month.invoicesDueCents -
      month.scheduledContributionsCents;
    series.push(balance);
    previous = balance;
  }

  return series;
}
